// ------------------------------------------------
// discoList.js
// Master list of electricity DISCOs with their
// VTUGate service_id values.
// service_id comes from GET /api/bills/vtugate_services/electricity
// ------------------------------------------------

export const DISCO_LIST = [
  {
    id: 'ekedc',
    label: 'EKEDC',
    fullName: 'Eko Electric',
    shortName: 'Eko',
    state: 'Lagos',
    coverage: 'Lagos Island, Lekki, Victoria Island',
    color: '#E53E3E',
    bgColor: '#FEE2E2',
    apiCode: 'ekedc',
    service_id: 326,
  },
  {
    id: 'ikedc',
    label: 'IKEDC',
    fullName: 'Ikeja Electric',
    shortName: 'Ikeja',
    state: 'Lagos',
    coverage: 'Lagos Mainland, Ikeja, Agege',
    color: '#D97706',
    bgColor: '#FEF3C7',
    apiCode: 'ikedc',
    service_id: 325,
  },
  {
    id: 'aedc',
    label: 'AEDC',
    fullName: 'Abuja Electric',
    shortName: 'Abuja',
    state: 'FCT',
    coverage: 'Abuja, Niger, Nasarawa, Kogi',
    color: '#059669',
    bgColor: '#D1FAE5',
    apiCode: 'aedc',
    service_id: 327,
  },
  {
    id: 'portharcourt',
    label: 'PHEDC',
    fullName: 'Port Harcourt Electric',
    shortName: 'PH Electric',
    state: 'Rivers',
    coverage: 'Port Harcourt, Rivers, Bayelsa',
    color: '#7C3AED',
    bgColor: '#EDE9FE',
    apiCode: 'portharcourt',
    service_id: 329,
  },
  {
    id: 'ibadan',
    label: 'IBEDC',
    fullName: 'Ibadan Electric',
    shortName: 'Ibadan',
    state: 'Oyo',
    coverage: 'Ibadan, Oyo, Ogun, Osun, Kwara',
    color: '#0284C7',
    bgColor: '#E0F2FE',
    apiCode: 'ibadan',
    service_id: 333,
  },
  {
    id: 'enugu',
    label: 'EEDC',
    fullName: 'Enugu Electric',
    shortName: 'Enugu',
    state: 'Enugu',
    coverage: 'Enugu, Anambra, Imo, Ebonyi, Abia',
    color: '#B45309',
    bgColor: '#FEF3C7',
    apiCode: 'enugu',
    service_id: 332,
  },
  {
    id: 'benin',
    label: 'BEDC',
    fullName: 'Benin Electric',
    shortName: 'Benin',
    state: 'Edo',
    coverage: 'Edo, Delta, Ekiti, Ondo',
    color: '#0F766E',
    bgColor: '#CCFBF1',
    apiCode: 'benin',
    service_id: 334,
  },
  {
    id: 'kaduna',
    label: 'KAEDCO',
    fullName: 'Kaduna Electric',
    shortName: 'Kaduna',
    state: 'Kaduna',
    coverage: 'Kaduna, Kebbi, Sokoto, Zamfara',
    color: '#C026D3',
    bgColor: '#FAE8FF',
    apiCode: 'kaduna',
    service_id: 331,
  },
  {
    id: 'kano',
    label: 'KEDCO',
    fullName: 'Kano Electric',
    shortName: 'Kano',
    state: 'Kano',
    coverage: 'Kano, Jigawa, Katsina',
    color: '#15803D',
    bgColor: '#DCFCE7',
    apiCode: 'kedco',
    service_id: 328,
  },
  {
    id: 'jos',
    label: 'JEDC',
    fullName: 'Jos Electric',
    shortName: 'Jos',
    state: 'Plateau',
    coverage: 'Plateau, Benue, Taraba, Gombe, Bauchi',
    color: '#1D4ED8',
    bgColor: '#DBEAFE',
    apiCode: 'jos',
    service_id: 330,
  },
  {
    id: 'yola',
    label: 'YEDC',
    fullName: 'Yola Electric',
    shortName: 'Yola',
    state: 'Adamawa',
    coverage: 'Adamawa, Borno, Yobe',
    color: '#9333EA',
    bgColor: '#F3E8FF',
    apiCode: 'yola',
    service_id: 336,
  },
  {
    id: 'aba',
    label: 'APLE',
    fullName: 'Aba Power',
    shortName: 'Aba',
    state: 'Abia',
    coverage: 'Aba, Abia',
    color: '#DC2626',
    bgColor: '#FEE2E2',
    apiCode: 'Aba',
    service_id: 335,
  },
];

export const getDiscoById = (id) =>
  DISCO_LIST.find((d) => d.id === id) || null;

export const getDiscoApiCode = (id) =>
  DISCO_LIST.find((d) => d.id === id)?.apiCode || id;

export const getDiscoServiceId = (id) =>
  DISCO_LIST.find((d) => d.id === id)?.service_id || null;